import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import CreateUserButton  from '../components/createuserbutton';
import { SendMessageButton } from '../components/sendmessagebutton';
import FetchChatButton from '../components/fetchuserchats';
import FetchChatRequestButton from '../components/fetchchatrequest';
import FetchChatBetweenUsersButton from '../components/fetchchatbwusers';
import { useState } from 'react';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <p className="text-black text-[2vmax] font-bold p-4">@dapp-sdk/messaging-push demo</p>
        <ConnectButton />
        <CreateUserButton/>
        <SendMessageButton />
        <FetchChatButton/>
        <FetchChatRequestButton/>
        <FetchChatBetweenUsersButton/>
      </main>

      
    </div>
  );
};

export default Home;
